function astrobee = generateAstrobeeStruct()
    m = 1.0;
    L = 1.0;
    A = L^2;
    astrobee = struct('m', m, ...
                      'L', L, ...
                      'I_zz', 1/12*m*A, ...
                      't_end', 4, ...
                      'damping', 0.0004, ...
                      'vx0', 0, ...
                      'vy0', 0, ...
                      'omega0', 0, ...
                      'x0', 0, ...
                      'y0', 10, ...
                      'theta0', 0, ...
                      'ThrustMagnitude', 1, ...
                      'ThrustAngle', 0, ...
                      'r_CP0', 0);

%{
    m = 1.0;
    L = 1.0;
    A = L^2;
    astrobee = struct('m', m, ...
                      'L', L, ...
                      'I_zz', 1/12*m*A, ...
                      't_end', 4, ...
                      'damping', 0.0004, ...
                      'vx0', 0, ...
                      'vy0', 0, ...
                      'omega0', 0, ...
                      'x0', 0, ...
                      'y0', 10, ...
                      'theta0', 0, ...
                      'ThrustMagnitude', 1, ...
                      'ThrustAngle', 0, ...
                      'r_CP0', 0);
%}
end